version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=todo
    ports:
      - 3307:3307
    volumes:
      - db:/var/lib/mysql
  client:
    build:
      context: client-side/
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    restart: unless-stopped
  app:
    depends_on:
      - mysqldb
    build:
      context: ./todo-api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=todo
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes: 
  db: