FROM node:16-alpine AS builder

# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
RUN yarn install


# Copy app files
COPY . .
# Build the app
# RUN yarn build


CMD ["yarn", "start:dev"]